
services:
  # j'utilise vault en mode dev 
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token-demo"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_TOKEN: "root-token-demo"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/scripts:/scripts
      - ./vault/policies:/policies
    networks:
      - secops

  # MySQL pour tester les rotations
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "oldpassword123"
      MYSQL_DATABASE: "demo"
    ports:
      - "3306:3306"
    networks:
      - secops

  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    environment:
      VAULT_ADDR: "http://vault:8200"
      # AppRole credentials 
      VAULT_ROLE_ID: "${API_ROLE_ID}"
      VAULT_SECRET_ID: "${API_SECRET_ID}"
    depends_on:
      - vault
      - mysql
    volumes:
      - ./ansible:/ansible:ro
      - ./logs:/logs
      - ./vault/scripts:/vault-scripts:ro
    networks:
      - secops
    
  dashboard:
      image: nginx:alpine
      container_name: dashboard
      ports:
        - "8080:80"
      volumes:
        - ./dashboard:/usr/share/nginx/html:ro
      networks:
        - secops


  jenkins:
    build: ./jenkins
    container_name: jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
      VAULT_ADDR: "http://vault:8200"
      # AppRole credentials
      VAULT_ROLE_ID: "${JENKINS_ROLE_ID}"
      VAULT_SECRET_ID: "${JENKINS_SECRET_ID}"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/config:/var/jenkins_home/init.groovy.d
      - ./jenkins/jobs:/var/jenkins_home/jobs
      - ./jenkins/pipelines:/jenkins/pipelines
      - ./ansible:/ansible
      - ./logs:/logs
      - ./vault/scripts:/vault-scripts:ro
    networks:
      - secops
    depends_on:
      - vault
      - api


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - secops

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - grafana_data:/var/lib/grafana
    networks:
      - secops

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - secops

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    command:
      - "--mysqld.address=mysql:3306"
      - "--mysqld.username=root"
    environment:
      MYSQLD_EXPORTER_PASSWORD: "oldpassword123"
    ports:
      - "9104:9104"
    networks:
      - secops
    depends_on:
      - mysql


networks:
  secops:
    driver: bridge

volumes:
  jenkins_home:
  prometheus_data:
  grafana_data:


