#!/bin/bash

VAULT_ADDR="http://localhost:8200"
VAULT_TOKEN="root-token-demo"

export VAULT_ADDR
export VAULT_TOKEN

echo "=== Initialisation Vault ==="

# 1. Activer KV v2 pour les secrets
echo "Activation KV secrets..."
vault secrets enable -path=secret kv-v2 2>/dev/null || echo "KV déjà activé"

# 2. Activer PKI pour les certificats
echo "Activation PKI..."
vault secrets enable pki 2>/dev/null || echo "PKI déjà activé"
vault secrets tune -max-lease-ttl=8760h pki

# 3. Générer une CA interne
echo "Création CA..."
vault write -field=certificate pki/root/generate/internal \
    common_name="Demo CA" \
    ttl=8760h > /tmp/CA_cert.crt

# 4. rôle pour générer des certificats
vault write pki/roles/internal \
    allowed_domains="local,localhost" \
    allow_subdomains=true \
    allow_glob_domains=true \
    max_ttl="720h" 

echo "Vault initialisé!"

echo "=== Ajout des policies ==="
vault policy write jenkins /policies/jenkins.hcl
vault policy write automation /policies/automation.hcl

# ========================
# Configuration AppRole
# ========================
echo "=== Configuration AppRole ==="

# 1. Activer AppRole auth method
vault auth enable approle 2>/dev/null || echo "AppRole déjà activé"

# 2. Créer le rôle pour l'API (accès complet aux secrets)
echo "Création du rôle API..."
vault write auth/approle/role/api-role \
    token_policies="automation" \
    token_ttl=1h \
    token_max_ttl=4h \
    secret_id_ttl=0 \
    secret_id_num_uses=0

# 3. Créer le rôle pour Jenkins (lecture seule + PKI)
echo "Création du rôle Jenkins..."
vault write auth/approle/role/jenkins-role \
    token_policies="jenkins" \
    token_ttl=1h \
    token_max_ttl=4h \
    secret_id_ttl=0 \
    secret_id_num_uses=0

# 4. Récupérer et sauvegarder les Role IDs
echo "Récupération des Role IDs..."
API_ROLE_ID=$(vault read -field=role_id auth/approle/role/api-role/role-id)
JENKINS_ROLE_ID=$(vault read -field=role_id auth/approle/role/jenkins-role/role-id)

# 5. Générer les Secret IDs
echo "Génération des Secret IDs..."
API_SECRET_ID=$(vault write -field=secret_id -f auth/approle/role/api-role/secret-id)
JENKINS_SECRET_ID=$(vault write -field=secret_id -f auth/approle/role/jenkins-role/secret-id)

# 6. Sauvegarder les credentials dans un fichier (pour les autres containers)
echo "Sauvegarde des credentials AppRole..."
cat > /scripts/approle-credentials.env << EOF
# AppRole Credentials - Generated by init.sh
# API AppRole
API_ROLE_ID=${API_ROLE_ID}
API_SECRET_ID=${API_SECRET_ID}

# Jenkins AppRole
JENKINS_ROLE_ID=${JENKINS_ROLE_ID}
JENKINS_SECRET_ID=${JENKINS_SECRET_ID}
EOF

echo "AppRole configuré!"
echo "  - API Role ID: ${API_ROLE_ID}"
echo "  - Jenkins Role ID: ${JENKINS_ROLE_ID}"